export interface UserModel  {
    "token": string,
    "email": string,
    "is_it_admin": string,
    "status_term": string,
    "mobile_no": number,
    "forgot_password_token": string,
    "client_id": string,
    "profile_pic": string,
    "is_active": string,
    "user_id": string,
    "display_name": string,
    "is_delete": string,
    "association_id": string,
    "created_on": Date,
    "update_log": Date,
    "association_type_term": string,
    "created_by": string,
    "seq_no": number,
    "user_name": string,
    "updated_on": Date,
    "user_type_term": string,
    "password": string,
    "updated_by": string,
    "is_default": "0"
  }